version: '3'
services:
  github.com/GiladLeef/DoctorSeuss:
    image: "docker.pkg.github.com/Doctor Seuss/github.com/GiladLeef/DoctorSeuss/github.com/GiladLeef/DoctorSeuss:latest"
    build:
      context: .
      args:
        - VUE_APP_URL=ws://localhost:8080
    environment:
      - PORT=80
    ports:
      - "80:80"
  Doctor Seuss:
    image: "docker.pkg.github.com/GiladLeef/DoctorSeuss/Doctor Seuss:latest"
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
